@startuml
 
package "PackageName" {
	'width:870;hight:500;x:290;y:410;'

class "Class1" as Class1{ 
	'width:250;hight:100;x:0;y:20;'
}
 

class "sdlfkhsDJFGHLSKDHFLKF" as sdlfkhsDJFGHLSKDHFLKF{ 
	'width:340;hight:100;x:330;y:90;'
}
 
'{"points": []}'
Class1 <-- Class2

class "Class3" as Class3{ 
	'width:250;hight:100;x:0;y:250;'
}
 
'{"points": []}'
Class1 <-- Class3
'{"points": [{"x": 455, "y": 230}]}'
Class2 <-- Class3

} 
 
@enduml