@startuml

package "mainMemory: HardwarePart" {

class "leNet: SoftwareComponent" as MemoryInterface {
#size: *
+receive(inst: inst.)
toProcess: inst.[]
latencies: *[]
}

abstract "ArrayList" as ArrayList {
+{abstract}read(address: integer): integer
}

object "loadUnit: MemoryAccessUnit" as loadUnit {
latencies = [4]
latencieszz = test
hallo = [welt]
nummer = 2
array = [10,20,3]
strArray = [h,w,h,f]
}

interface CacheInterface {
+ {static} readFromNextLevel(function: MemoryInterconnect.read, address: integer): data
+writeToNextLevel(function: MemoryInterconnect.write, address: integer, data: data)
}

ArrayList "1"*--"0..*" CacheInterface
MemoryInterface <|-left- MemoryInterface
loadUnit "0..*"<--"0..1" ArrayList : "write():data"

}

@enduml
